import type { Book } from "./types";

/**
 * Dataset local de demonstração. Usado quando o Supabase ainda não está
 * configurado (sem NEXT_PUBLIC_SUPABASE_URL no .env), para o jogo rodar
 * de ponta a ponta em desenvolvimento. Em produção os livros vêm do banco.
 *
 * As capas usam a Open Library Covers API (por ISBN), então os modos visuais
 * (capa/blur/silhueta) funcionam mesmo offline.
 */
export const SEED_BOOKS: Book[] = [
  {
    id: 1,
    title: "Dom Casmurro",
    original_title: null,
    author: "Machado de Assis",
    year: 1899,
    country: "Brasil",
    language: "Português",
    genre: "Romance",
    subgenre: "Realismo",
    pages: 256,
    cover_url: "https://covers.openlibrary.org/b/isbn/9788525406958-L.jpg",
    description:
      "Bentinho narra sua história com Capitú e a dúvida que o consome: teria ela o traído com seu melhor amigo?",
    popularity: 95,
    difficulty: "easy",
    sales_estimate: 5,
    tags: ["ciúme", "narrador não confiável", "Rio de Janeiro", "clássico"],
  },
  {
    id: 2,
    title: "O Pequeno Príncipe",
    original_title: "Le Petit Prince",
    author: "Antoine de Saint-Exupéry",
    year: 1943,
    country: "França",
    language: "Francês",
    genre: "Fábula",
    subgenre: "Infantil",
    pages: 96,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780156012195-L.jpg",
    description:
      "Um piloto cai no deserto e encontra um pequeno príncipe que viajou de asteroide em asteroide.",
    popularity: 99,
    difficulty: "easy",
    sales_estimate: 200,
    tags: ["deserto", "rosa", "raposa", "infância", "filosofia"],
  },
  {
    id: 3,
    title: "Harry Potter e a Pedra Filosofal",
    original_title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    year: 1997,
    country: "Reino Unido",
    language: "Inglês",
    genre: "Fantasia",
    subgenre: "Juvenil",
    pages: 264,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780747532699-L.jpg",
    description:
      "Um garoto órfão descobre no seu aniversário de 11 anos que é bruxo e vai estudar em Hogwarts.",
    popularity: 100,
    difficulty: "easy",
    sales_estimate: 120,
    tags: ["magia", "escola", "amizade", "bruxos", "órfão"],
  },
  {
    id: 4,
    title: "O Senhor dos Anéis: A Sociedade do Anel",
    original_title: "The Fellowship of the Ring",
    author: "J. R. R. Tolkien",
    year: 1954,
    country: "Reino Unido",
    language: "Inglês",
    genre: "Fantasia",
    subgenre: "Alta fantasia",
    pages: 576,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780618574940-L.jpg",
    description:
      "Frodo herda um anel poderoso e parte numa jornada para destruí-lo antes que o mal domine a Terra-média.",
    popularity: 98,
    difficulty: "easy",
    sales_estimate: 150,
    tags: ["anel", "hobbit", "aventura", "épico", "Terra-média"],
  },
  {
    id: 5,
    title: "1984",
    original_title: "Nineteen Eighty-Four",
    author: "George Orwell",
    year: 1949,
    country: "Reino Unido",
    language: "Inglês",
    genre: "Ficção Científica",
    subgenre: "Distopia",
    pages: 416,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    description:
      "Num regime totalitário que tudo vigia, Winston Smith tenta preservar sua liberdade de pensar.",
    popularity: 97,
    difficulty: "easy",
    sales_estimate: 30,
    tags: ["distopia", "vigilância", "totalitarismo", "Grande Irmão"],
  },
  {
    id: 6,
    title: "Cem Anos de Solidão",
    original_title: "Cien años de soledad",
    author: "Gabriel García Márquez",
    year: 1967,
    country: "Colômbia",
    language: "Espanhol",
    genre: "Romance",
    subgenre: "Realismo mágico",
    pages: 448,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    description:
      "A ascensão e queda da família Buendía ao longo de gerações na cidade mítica de Macondo.",
    popularity: 90,
    difficulty: "medium",
    sales_estimate: 50,
    tags: ["realismo mágico", "família", "Macondo", "gerações"],
  },
  {
    id: 7,
    title: "Grande Sertão: Veredas",
    original_title: null,
    author: "João Guimarães Rosa",
    year: 1956,
    country: "Brasil",
    language: "Português",
    genre: "Romance",
    subgenre: "Regionalismo",
    pages: 608,
    cover_url: "https://covers.openlibrary.org/b/isbn/9788520925157-L.jpg",
    description:
      "O jagunço Riobaldo narra sua vida no sertão, seu amor por Diadorim e um possível pacto com o diabo.",
    popularity: 80,
    difficulty: "hard",
    sales_estimate: 2,
    tags: ["sertão", "jagunço", "pacto", "regionalismo"],
  },
  {
    id: 8,
    title: "Capitães da Areia",
    original_title: null,
    author: "Jorge Amado",
    year: 1937,
    country: "Brasil",
    language: "Português",
    genre: "Romance",
    subgenre: "Social",
    pages: 288,
    cover_url: "https://covers.openlibrary.org/b/isbn/9788535914085-L.jpg",
    description:
      "A vida de um grupo de meninos de rua em Salvador, entre pequenos crimes, amizade e sonhos.",
    popularity: 85,
    difficulty: "medium",
    sales_estimate: 3,
    tags: ["meninos de rua", "Salvador", "social", "Bahia"],
  },
  {
    id: 9,
    title: "O Hobbit",
    original_title: "The Hobbit",
    author: "J. R. R. Tolkien",
    year: 1937,
    country: "Reino Unido",
    language: "Inglês",
    genre: "Fantasia",
    subgenre: "Aventura",
    pages: 336,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    description:
      "Bilbo Bolseiro embarca com anões e um mago numa jornada para recuperar um tesouro guardado por um dragão.",
    popularity: 94,
    difficulty: "easy",
    sales_estimate: 100,
    tags: ["dragão", "tesouro", "hobbit", "aventura", "anões"],
  },
  {
    id: 10,
    title: "Orgulho e Preconceito",
    original_title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    country: "Reino Unido",
    language: "Inglês",
    genre: "Romance",
    subgenre: "Costumes",
    pages: 424,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    description:
      "Elizabeth Bennet e o orgulhoso Sr. Darcy superam mal-entendidos e o próprio orgulho até se entenderem.",
    popularity: 92,
    difficulty: "medium",
    sales_estimate: 20,
    tags: ["romance de época", "casamento", "orgulho", "Inglaterra"],
  },
  {
    id: 11,
    title: "A Menina que Roubava Livros",
    original_title: "The Book Thief",
    author: "Markus Zusak",
    year: 2005,
    country: "Austrália",
    language: "Inglês",
    genre: "Drama",
    subgenre: "Histórico",
    pages: 480,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    description:
      "Na Alemanha nazista, Liesel encontra conforto em livros roubados, com a Morte como narradora.",
    popularity: 88,
    difficulty: "medium",
    sales_estimate: 16,
    tags: ["nazismo", "livros", "Morte narradora", "amizade"],
  },
  {
    id: 12,
    title: "O Alquimista",
    original_title: null,
    author: "Paulo Coelho",
    year: 1988,
    country: "Brasil",
    language: "Português",
    genre: "Fábula",
    subgenre: "Filosófico",
    pages: 208,
    cover_url: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    description:
      "O pastor Santiago cruza o deserto atrás de um tesouro e descobre sua Lenda Pessoal pelo caminho.",
    popularity: 93,
    difficulty: "easy",
    sales_estimate: 65,
    tags: ["deserto", "sonho", "jornada", "Lenda Pessoal"],
  },
];
