import type { ModeDef } from "./types";

/**
 * Registro central dos modos de jogo. Esta é a ÚNICA fonte de verdade:
 * adicionar um modo = adicionar um objeto aqui (e, se for um tipo de pista
 * inédito, um caso no componente Clue e na função de round). Não há páginas
 * nem rotas por modo.
 */
export const MODES: ModeDef[] = [
  // ----------------------------- comparação ------------------------------
  {
    id: "daily",
    name: "Diário",
    emoji: "📅",
    description: "Um livro por dia, igual para todos. Dicas a cada palpite.",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "unlimited",
    name: "Ilimitado",
    emoji: "♾️",
    description: "Livros infinitos, sem limite de partidas.",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },
  {
    id: "age",
    name: "Idade do Livro",
    emoji: "⏳",
    description: "Descubra o livro comparando só quão antigo ele é.",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book:year",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },
  {
    id: "pages",
    name: "Número de Páginas",
    emoji: "📄",
    description: "Descubra o livro comparando só o número de páginas.",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book:pages",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },
  {
    id: "sales",
    name: "Vendas",
    emoji: "💰",
    description: "Descubra o livro comparando as cópias vendidas.",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book:sales",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },

  // -------------------------------- pistas -------------------------------
  {
    id: "quote",
    name: "Frase",
    emoji: "💬",
    description: "De qual livro é esta frase?",
    group: "pistas",
    guessType: "book",
    clueType: "quote",
    source: "quote:quote",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "opening",
    name: "Primeira Frase",
    emoji: "📖",
    description: "Adivinhe o livro pela sua primeira frase.",
    group: "pistas",
    guessType: "book",
    clueType: "opening",
    source: "quote:opening",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "closing",
    name: "Última Frase",
    emoji: "🔚",
    description: "Adivinhe o livro pela sua última frase.",
    group: "pistas",
    guessType: "book",
    clueType: "closing",
    source: "quote:closing",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "character-quote",
    name: "Fala de Personagem",
    emoji: "🗣️",
    description: "De qual livro é esta fala?",
    group: "pistas",
    guessType: "book",
    clueType: "character-quote",
    source: "quote:character",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "character",
    name: "Personagem",
    emoji: "🧑",
    description: "Adivinhe o livro pela descrição de um personagem.",
    group: "pistas",
    guessType: "book",
    clueType: "character-desc",
    source: "character",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "book-by-character",
    name: "Livro pelo Personagem",
    emoji: "👤",
    description: "Dado o nome de um personagem, qual é o livro?",
    group: "pistas",
    guessType: "book",
    clueType: "character-name",
    source: "character",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "chapter",
    name: "Capítulo",
    emoji: "📑",
    description: "Adivinhe o livro pelo nome de um capítulo.",
    group: "pistas",
    guessType: "book",
    clueType: "chapter",
    source: "chapter",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "adaptation",
    name: "Adaptação",
    emoji: "🎬",
    description: "Qual livro deu origem a esta adaptação?",
    group: "pistas",
    guessType: "book",
    clueType: "adaptation",
    source: "adaptation",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "emoji",
    name: "Emoji",
    emoji: "😀",
    description: "Adivinhe o livro representado pelos emojis.",
    group: "pistas",
    guessType: "book",
    clueType: "emoji",
    source: "emoji",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "synopsis",
    name: "Sinopse",
    emoji: "📝",
    description: "Adivinhe o livro por uma pequena sinopse.",
    group: "pistas",
    guessType: "book",
    clueType: "synopsis",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
    requires: "description",
  },
  {
    id: "tags",
    name: "Tags",
    emoji: "🏷️",
    description: "Adivinhe o livro por palavras-chave.",
    group: "pistas",
    guessType: "book",
    clueType: "tags",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: true,
    available: true,
  },
  {
    id: "timeline",
    name: "Timeline",
    emoji: "🕰️",
    description: "Pistas sobre ano, país e gênero, uma de cada vez.",
    group: "pistas",
    guessType: "book",
    clueType: "timeline",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: true,
    available: true,
  },
  {
    id: "cover",
    name: "Capa (Zoom)",
    emoji: "🖼️",
    description: "A capa aparece com zoom; abre mais a cada erro.",
    group: "pistas",
    guessType: "book",
    clueType: "cover-zoom",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },
  {
    id: "blur",
    name: "Capa Borrada",
    emoji: "🌫️",
    description: "A capa começa borrada e vai clareando a cada erro.",
    group: "pistas",
    guessType: "book",
    clueType: "cover-blur",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },
  {
    id: "silhouette",
    name: "Silhueta",
    emoji: "⬛",
    description: "Só a silhueta da capa; detalhes surgem a cada erro.",
    group: "pistas",
    guessType: "book",
    clueType: "cover-silhouette",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },

  // -------------------------------- autor --------------------------------
  {
    id: "author",
    name: "Autor",
    emoji: "✍️",
    description: "Mostramos o título; você descobre quem escreveu.",
    group: "autor",
    guessType: "author",
    clueType: "book-title",
    source: "book",
    compare: "author",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "author-guess",
    name: "Adivinhe o Autor",
    emoji: "🧑‍🎨",
    description: "Estilo Loldle: compare país, idioma, época e gênero.",
    group: "autor",
    guessType: "author",
    clueType: "none",
    source: "author",
    compare: "author",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },

  // ------------------------------- especial ------------------------------
  {
    id: "mixed",
    name: "Misto",
    emoji: "🎲",
    description: "Cada rodada sorteia um modo diferente.",
    group: "especial",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
    mixOf: [
      "quote",
      "opening",
      "character",
      "book-by-character",
      "emoji",
      "tags",
      "timeline",
      "cover",
      "blur",
      "silhouette",
      "synopsis",
      "adaptation",
      "chapter",
    ],
  },
];

const BY_ID = new Map(MODES.map((m) => [m.id, m]));

export function getMode(id: string): ModeDef | undefined {
  return BY_ID.get(id);
}

export function listModes(): ModeDef[] {
  return MODES;
}

export function modesByGroup(): Record<string, ModeDef[]> {
  const groups: Record<string, ModeDef[]> = {};
  for (const m of MODES) (groups[m.group] ??= []).push(m);
  return groups;
}
