import type { ModeDef } from "./types";

/**
 * Registro central dos modos de jogo. Esta é a ÚNICA fonte de verdade:
 * adicionar um modo = adicionar um objeto aqui (e, se for um tipo de pista
 * inédito, um caso no componente Clue e na função de round). Não há páginas
 * nem rotas por modo.
 */
export const MODES: ModeDef[] = [
  // ----------------------------- comparação ------------------------------
  {
    id: "daily",
    emoji: "📅",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "unlimited",
    emoji: "♾️",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },
  {
    id: "age",
    emoji: "⏳",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 8,
    progressive: false,
    available: true,
    mechanic: "higher-lower",
    statKey: "year",
  },
  {
    id: "pages",
    emoji: "📄",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 8,
    progressive: false,
    available: true,
    mechanic: "higher-lower",
    statKey: "pages",
  },
  {
    id: "sales",
    emoji: "💰",
    group: "comparação",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 8,
    progressive: false,
    available: true,
    mechanic: "higher-lower",
    statKey: "sales_estimate",
  },

  // --------------------------------- frases -------------------------------
  {
    id: "opening",
    emoji: "📖",
    group: "frases",
    guessType: "book",
    clueType: "opening",
    source: "quote:opening",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "closing",
    emoji: "🔚",
    group: "frases",
    guessType: "book",
    clueType: "closing",
    source: "quote:closing",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  // ------------------------ adivinhe pelo livro ---------------------------
  {
    id: "character",
    emoji: "🧑",
    group: "livro",
    guessType: "book",
    clueType: "character-desc",
    source: "character",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "book-by-character",
    emoji: "👤",
    group: "livro",
    guessType: "book",
    clueType: "character-name",
    source: "character",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "chapter",
    emoji: "📑",
    group: "livro",
    guessType: "book",
    clueType: "chapter",
    source: "chapter",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "adaptation",
    emoji: "🎬",
    group: "livro",
    guessType: "book",
    clueType: "adaptation",
    source: "adaptation",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },

  // ----------------------------- outras pistas ----------------------------
  {
    id: "emoji",
    emoji: "😀",
    group: "outras-pistas",
    guessType: "book",
    clueType: "emoji",
    source: "emoji",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "synopsis",
    emoji: "📝",
    group: "outras-pistas",
    guessType: "book",
    clueType: "synopsis",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
    requires: "description",
  },
  {
    id: "tags",
    emoji: "🏷️",
    group: "outras-pistas",
    guessType: "book",
    clueType: "tags",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: true,
    available: true,
  },
  {
    id: "timeline",
    emoji: "🕰️",
    group: "outras-pistas",
    guessType: "book",
    clueType: "timeline",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: true,
    available: true,
  },

  // --------------------------------- capa ---------------------------------
  {
    id: "cover",
    emoji: "🖼️",
    group: "capa",
    guessType: "book",
    clueType: "cover-zoom",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },
  {
    id: "blur",
    emoji: "🌫️",
    group: "capa",
    guessType: "book",
    clueType: "cover-blur",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },
  {
    id: "silhouette",
    emoji: "⬛",
    group: "capa",
    guessType: "book",
    clueType: "cover-silhouette",
    source: "book",
    compare: "book",
    maxGuesses: 5,
    progressive: true,
    available: true,
    requires: "cover_url",
  },

  // -------------------------------- autor --------------------------------
  {
    id: "author",
    emoji: "✍️",
    group: "autor",
    guessType: "author",
    clueType: "book-title",
    source: "book",
    compare: "author",
    maxGuesses: 6,
    progressive: false,
    available: true,
  },
  {
    id: "author-guess",
    emoji: "🧑‍🎨",
    group: "autor",
    guessType: "author",
    clueType: "none",
    source: "author",
    compare: "author",
    maxGuesses: 8,
    progressive: false,
    available: true,
  },

  // ------------------------------- especial ------------------------------
  {
    id: "mixed",
    emoji: "🎲",
    group: "especial",
    guessType: "book",
    clueType: "none",
    source: "book",
    compare: "book",
    maxGuesses: 6,
    progressive: false,
    available: true,
    mixOf: [
      "opening",
      "character",
      "book-by-character",
      "emoji",
      "tags",
      "timeline",
      "cover",
      "blur",
      "silhouette",
      "synopsis",
      "adaptation",
      "chapter",
    ],
  },
];

const BY_ID = new Map(MODES.map((m) => [m.id, m]));

export function getMode(id: string): ModeDef | undefined {
  return BY_ID.get(id);
}

export function listModes(): ModeDef[] {
  return MODES;
}

export function modesByGroup(): Record<string, ModeDef[]> {
  const groups: Record<string, ModeDef[]> = {};
  for (const m of MODES) (groups[m.group] ??= []).push(m);
  return groups;
}
